# Basic
plugins: [jekyll-paginate]
title: LineCutFeng
subtitle: 知原解理、剖线析构
welcome_message: 欢迎来到我的世界! 
description: 嗨，我是 LineCutFeng，一名住在帝都的Android程序猿。
creator: <a href="http://www.linecutfeng.com">@LineCutFeng</a>

url: "http://www.linecutfeng.com"

permalink: /:categories/:title

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: GitHub,     in_site: false,  description: LineCutFeng's GitHub,    url: 'https://github.com/LineCutFeng'}
    - {title: 目录,        in_site: true,  description: 博客目录,               url: '/timeline'}
    - {title: 关于,        in_site: true,  description: 关于作者 LineCutFeng,       url: '/info/about'}
    


gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-redirect-from


# Pagination
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: LineCutFeng
    # duoshuo:
# Social
social:
    weibo: LineCutFeng
    github: LineCutFeng
    # twitter: LineCutFeng
    rss: /feed.xml
    mail: LineCutFeng@gmail.com
    copyright: http://choosealicense.online

# Google Analytics
ga:
    id: UA-82493667-1
    host: www.LineCutFeng.com
